apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ndd-rbac-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndd-proxy-role
subjects:
- kind: ServiceAccount
  name: ndd-rbac
  namespace: ndd-system
