apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ndd-rbac-leader-election-rolebinding
  namespace: ndd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ndd-leader-election-role
subjects:
- kind: ServiceAccount
  name: ndd-rbac
  namespace: ndd-system
