apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: rbac
  name: ndd-rbac-metrics-service
  namespace: ndd-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: rbac
